Update README.md
conniepope/Project-1 pull request #29
Opened 2019-06-18 20:53 UTC by arajis06

update ReadMe Photo

2019-06-18 21:42 UTC, conniepope commented on README.md
> +Are you a FOODIE or just someome who enjoys traveling? Explore local restaurants and your tastebuds on your journey.
was this supposed to say "and take your tastebuds on a journey"?

2019-06-18 21:44 UTC, conniepope requested changes
I think the line you changed is off a little in the wording. Can you fix it?

2019-06-18 23:27 UTC, arajis06 reviewed
fixed wording back to original

2019-06-19 00:18 UTC, conniepope approved these changes

2019-06-19 00:19 UTC, conniepope approved these changes

2019-06-19 00:19 UTC, conniepope approved these changes

2019-06-19 00:19 UTC, merged